name: Release Package on PyPi
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  poetry-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: release to PyPI
        uses: moj-analytical-services/actions-poetry-pypi-release@v1
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
